# Generated by Django 2.0 on 2018-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainday',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainresult',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainresult',
            name='measure',
            field=models.CharField(default='кг', max_length=5),
        ),
    ]
