# Generated by Django 2.0 on 2018-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20180108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainday',
            name='mood',
            field=models.CharField(max_length=5),
        ),
    ]
