runtime: python
env: flex
env_variables:
    DJANGO_SETTINGS_MODULE: project.gae_settings
entrypoint: gunicorn -b :$PORT project.wsgi

beta_settings:
    cloud_sql_instances: hard-gain:europe-west1:hardgain-db

runtime_config:
  python_version: 3
