runtime: python
env: flex
env_variables:
    DJANGO_SETTINGS_MODULE: project.gae_settings
entrypoint: gunicorn -b :$PORT project.wsgi

beta_settings:
    cloud_sql_instances: cloudtest-171813:europe-west1:test-cloud-sql

runtime_config:
  python_version: 3
