# Generated by Django 2.0 on 2018-01-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
