# Generated by Django 2.0 on 2018-01-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_exercise_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='weekday',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=5),
        ),
    ]
